/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.DeleteController;
import controller.InsertController;
import controller.UpdateController;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.DBConnection;
import model.DBSearch;

/**
 *
 * @author C TECH
 */
public class ItemM extends javax.swing.JFrame {

    /**
     * Creates new form ItemM
     */
    public ItemM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        supplierBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemnaTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        quanTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        supTF = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Inums = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        supNameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        supIdTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supCNameTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phoINT = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(87, 166, 161));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierBtn.setBackground(new java.awt.Color(0, 0, 255));
        supplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supplierBtnMousePressed(evt);
            }
        });
        supplierBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Item Manage");
        supplierBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, 26));

        jPanel2.add(supplierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 56));

        itemBtn.setBackground(new java.awt.Color(0, 0, 102));
        itemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Supplier Manage");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout itemBtnLayout = new javax.swing.GroupLayout(itemBtn);
        itemBtn.setLayout(itemBtnLayout);
        itemBtnLayout.setHorizontalGroup(
            itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemBtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        itemBtnLayout.setVerticalGroup(
            itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(itemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 470));

        jTabbedPane3.setBackground(new java.awt.Color(0, 51, 204));

        jPanel1.setBackground(new java.awt.Color(172, 225, 175));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 164, 16));

        numTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTFActionPerformed(evt);
            }
        });
        jPanel1.add(numTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 204, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 136, -1));

        itemnaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnaTFActionPerformed(evt);
            }
        });
        jPanel1.add(itemnaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 204, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Supplier ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 164, 16));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 164, 16));

        quanTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanTFActionPerformed(evt);
            }
        });
        jPanel1.add(quanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 204, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 94, -1));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 94, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 94, -1));

        jPanel1.add(supTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 204, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/istockphoto-1787508974-170x170.jpg"))); // NOI18N
        jLabel12.setText("    Search Details");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 170, 110));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel13.setText("SEARCH DETAILS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 170, 30));

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setFont(new java.awt.Font("Sitka Subheading", 1, 15)); // NOI18N
        jLabel14.setText("Enter Item Number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 160, 20));

        Inums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InumsActionPerformed(evt);
            }
        });
        jPanel1.add(Inums, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 170, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 10, 470));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "item_Name", "item_Number", "supplier_ID", "quantity"
            }
        ));
        jScrollPane1.setViewportView(itemTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 520, 190));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("EXIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 94, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 90, -1));

        jTabbedPane3.addTab("tab2", jPanel1);

        jPanel7.setBackground(new java.awt.Color(172, 225, 175));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(supNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 206, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Supplier ID");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 136, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Supplier Name");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 136, -1));

        supIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supIdTFActionPerformed(evt);
            }
        });
        jPanel7.add(supIdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 206, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Company Name");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 136, -1));

        addTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTFActionPerformed(evt);
            }
        });
        jPanel7.add(addTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 206, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 136, -1));

        supCNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supCNameTFActionPerformed(evt);
            }
        });
        jPanel7.add(supCNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 206, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 136, -1));

        phoINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoINTActionPerformed(evt);
            }
        });
        jPanel7.add(phoINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 206, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Insert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 71, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, -1));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("EXIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 94, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Inventory-Management-c.jpg"))); // NOI18N
        jLabel15.setText("jLabel1");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 350, 450));

        jTabbedPane3.addTab("tab1", jPanel7);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, 740, 500));

        setSize(new java.awt.Dimension(877, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supplierBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtnMousePressed
       
        setColor(supplierBtn);
        resetColor(itemBtn);
jTabbedPane3.setSelectedIndex(0);
// TODO add your handling code here:
    }//GEN-LAST:event_supplierBtnMousePressed

    private void itemBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemBtnMousePressed
tableLoad();        
 setColor(itemBtn);
resetColor(supplierBtn);

jTabbedPane3.setSelectedIndex(1);

        try {
            Statement stmt = DBConnection.getStatementConnection();
            ResultSet rs= stmt.executeQuery("SELECT sid FROM supplier");

         while(rs.next()){
             String supid = rs.getString("sid");
             supTF.addItem(supid);
         }
        } catch (Exception e) {
        }

        try {
            Statement stmt = DBConnection.getStatementConnection();
         ResultSet rs = stmt.executeQuery("SELECT sid From supplier");
         
            while (rs.next()){
                String suppid= rs.getString("sid");
                supTF.addItem(suppid);
            }
            DBConnection.closeCon();
        } catch (Exception e) {
        }
// TODO add your handling code here:
    }//GEN-LAST:event_itemBtnMousePressed

    private void supIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supIdTFActionPerformed

    private void itemnaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnaTFActionPerformed

    private void numTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTFActionPerformed

    private void addTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTFActionPerformed

    private void supCNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supCNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supCNameTFActionPerformed

    private void phoINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoINTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoINTActionPerformed

    private void quanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String itemName = itemnaTF.getText();
        String number= numTF.getText();
        String qua= quanTF.getText();
        
        String supID = supTF.getSelectedItem().toString();
        int phone=Integer.parseInt(qua);
        InsertController.insertitem(itemName, number,supID,qua);
        tableLoad();
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String supName= supNameTF.getText();
       String supId= supIdTF.getText();
       String supllierCName=supIdTF.getText();
       String address= addTF.getText();
       String phonee=phoINT.getText();
       int phone=Integer.parseInt(phonee);
       
      InsertController.insertsupplier(supName, supId, supName, address, phone);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void InumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InumsActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try {
            String inum = Inums.getText();
            
            ResultSet rs = new DBSearch().searchitem(inum);
            
               while(rs.next()){
               String i_num = rs.getString("item_Number");
               String i_name = rs.getString("item_Name");
               String quan= rs.getString("quantity");
               
          numTF.setText(i_num);
          itemnaTF.setText(i_name);
          quanTF.setText(quan);
                   System.out.println(i_name);
           }
        
        } catch (Exception e) {
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String Inum = numTF.getText();
        
        if(Inum !=null){
            DeleteController.deleteInum(Inum);
        }
        tableLoad();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String iname = itemnaTF.getText();
String inum =numTF.getText();
String supid=supTF.getSelectedItem().toString();
String quan= quanTF.getText();

UpdateController.UpdateForm(inum, iname, supid, quan);
 tableLoad();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        itemnaTF.setText("");
        numTF.setText("");
       
        quanTF.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   supNameTF.setText("");
        supIdTF.setText("");
       supCNameTF.setText("");
       addTF.setText("");
       phoINT.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    
    void setColor(JPanel panel){
    panel.setBackground(new Color(0,0,255));
    
    }
    void resetColor(JPanel panel){
    
    panel.setBackground(new Color(0,0,102));
    
    }
    
    
    public void tableLoad(){
        ResultSet rs = new DBSearch().searchAllitems();
            
            try {
            DefaultTableModel tb1Model = (DefaultTableModel)itemTable.getModel();
            tb1Model.setRowCount(0);
            
            while(rs.next()){
                String inum= rs.getString("item_Number");
                String iname= rs.getString("item_Name");
                String isup= rs.getString("supplier_ID");
                String quan= rs.getString("quantity");
                
                String tbData[]= {iname,inum ,isup, quan};
                tb1Model.addRow(tbData);
                
            }
            
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Inums;
    private javax.swing.JTextField addTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel itemBtn;
    private javax.swing.JTable itemTable;
    private javax.swing.JTextField itemnaTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField numTF;
    private javax.swing.JTextField phoINT;
    private javax.swing.JTextField quanTF;
    private javax.swing.JTextField supCNameTF;
    private javax.swing.JTextField supIdTF;
    private javax.swing.JTextField supNameTF;
    private javax.swing.JComboBox<String> supTF;
    private javax.swing.JPanel supplierBtn;
    // End of variables declaration//GEN-END:variables
}
